version: '3'

services:
  db: 
    build: ./db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: bambu
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      DATABASE_HOST: db
    restart: always
    volumes:
      - mysqldata
  
  app:
    build: ./
    environment:
      MYSQL_DATABASE: bambu
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
      DATABASE_HOST: db
    ports: 
      - "8080:8080"
    depends_on: 
      - db
    restart: on-failure


  